CREATE DATABASE IF NOT EXISTS estudiantes CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE estudiantes;

CREATE TABLE IF NOT EXISTS estudiantes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  apellido VARCHAR(100) NOT NULL,
  correo VARCHAR(150) NOT NULL,
  telefono VARCHAR(50),
  curso VARCHAR(150) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_correo (correo),
  INDEX idx_curso (curso)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
